### ISSUE TITLE
Resolver. client: share common code

### ISSUE THREAD

**Issue by hannesm** [mirage/ocaml-dns#168]
and enable client to easily use a resolver as cache

**Comment by yomimono** [comment]
We (@linse and I) need this for [qubes-mirage-firewall](https://github.com/mirage/qubes-mirage-firewall), where we're implementing lookups for rules with hostnames in them.  Currently we use the resolver to cache, but this awkward because:
  * we need to fake network traffic from the firewall in order to begin requests
  * we need to reimplement CNAME following logic
  * we need to reimplement NXDomain logic
  * we don't get TCP for free; our code is currently UDP-only

We end up duplicating or reinventing a fair amount of code which it seems we would rather use from the client.  For our application, an interface like `gethostbyname` but with caching and UDP support would be appropriate.

We have the additional problem that for the firewall, we can't use an API that monopolizes the network stack -- we need to distinguish between packets for the firewall itself (those involved in DNS transactions) and those for downstream NAT clients (packets which match entries in the NAT table).

**Comment by yomimono** [comment]
@hannesm , @linse , and I attempted to use the existing client interface in the firewall; that retrofit is at https://github.com/yomimono/qubes-mirage-firewall/commit/35a7bb98d2204de11b5b89d4eb8f55bafec5ba97 , but was reverted because no traffic is sent.

**Comment by hannesm** [comment]
when I tried the resolver yesterday evening, it looks like its `` `Recursive `` mode, as released with 4.0.0, does not work properly. if you run into issues, have a try at the `` `Stub `` mode (which requires a forwarding resolver in the zone, as done in https://github.com/roburio/unikernels/blob/master/stub-resolver/unikernel.ml)

**Comment by yomimono** [comment]
Can you elaborate more on "does not work properly"?  We're only testing with a small number of domain names but haven't noticed anything not attributable to our own errors.

**Comment by hannesm** [comment]
@yomimono for me, resolving e.g. `avatars0.githubusercontent.com` fails atm since some DNS reply is not properly handled

**Comment by hannesm** [comment]
at the retreat late September 2019, some work was achieved on this front:
- #191 added a cache for the DNS client (with further enhances in #192) -- the Dns_cache module (dns.cache findlib library) originates from Dns_resolver_cache //cc @cfcs @linse @olleolleolle
- #192 also caches negative (valid) responses nxdomain and nodata
- we adapted the mirage-qubes-firewall branch to use the dns client instead of the resolver (see https://github.com/yomimono/qubes-mirage-firewall/commit/7b705a3e68d5029ac03c51668a23be844bbbed53 and https://github.com/yomimono/qubes-mirage-firewall/commit/2bab7752225833e7c8989625a65e25ba520b540c) -- a fresh new approach with less code than the previous one (and also, the resolution actually results in resolved names (not sure if this is bug-free though))
- the resolver is on its way out

there are still some work items for the (caching) client to be ready and useful:
- timeout (i.e. if the upstream DNS resolver does not reply)
- retransmission (if using UDP is worth it -- I'm still undecided about this)
- reusing a single (TCP) connection to the upstream resolver for multiple queries
- if multiple `getaddrinfo` are in transit to the same upstream (using the same source port), the replies need to be matched correctly (since they may be out of order) -- also needed for reusing TCP
- other things i forgot (if you've something in mind, please say so)

to come back to the topic of this issue, the sharing already happened (dns_cache); further client code may inherit from the resolver code. I'll close this issue, if you feel there are more concrete issues (such as "showstoppers to use dns-client in qubes-firewall"), please open new issues for them.
