### ISSUE TITLE
mDNS Packet.q_unicast interface confusing

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-dns#41]
The `Packet.q_unicast` field is used to specify that a querier is willing to receive unicast responses from a multicast message. The mDNS RFC Sec 5.4 <https://tools.ietf.org/html/rfc6762#section-5.4> says that it does this via the reserved top bit in the question class field. Usually, this field is `Q_IN` = 0x0001.

`QM` is the normal 0-top-bit value. `QU` is the special, unicast-marked packet for mDNS. If you are using `ocaml-dns` to transmit normal non-mDNS DNS, the `q_unicast` field should be (confusingly) set to `QM` otherwise the class will be unknown for classical servers (which may then refuse to forward the query or otherwise operate as expected).

**Comment by dsheets** [comment]
However this gets resolved, the resolution should include documentation in the `.mli`.

**Comment by infidel** [comment]
Even though the names of "q_unicast", "QM" and "QU" were chosen to match the RFC, yes it is a bit weird to have to set q_unicast=QM for non-mDNS DNS.

I guess there is no way to have a default value for a record field in OCaml? Coming from a C++/C#/Python background, I might use a constructor or other function that defaults to QM so that non-mDNS usage doesn't have to specify the value of the field at all. A constructor function is an option here, but doesn't help backward compatibility.

A simpler option would be to just rename "QM" and "QU" to something more descriptive that reflects the fact that a value of zero for the bit can mean either "non-mDNS" or "mDNS requesting multicast response" (depending on the UDP source port number). I don't have a good suggestion for these names yet.

Having three variant tags would make marshalling a bit more intuitive but the parse function would still have to one of two values for zero, so that's not ideal either.

**Comment by dsheets** [comment]
I think a constructor function for the `question` type and some documentation on the question type pointing to the constructor function and describing the meaning of the `q_unicast` field would solve the problem. I've just run into an instance of use where mDNS was not being used by `q_unicast` was set to `QU` (presumably because the DNS query was not multicast).

To really clarify the situation, the constructors could be renamed from `QM` to `Q_Normal` and `QU` to `Q_mDNS_Unicast` or similar.

**Comment by infidel** [comment]
OK Q_Normal and Q_mDNS_Unicast makes sense. In that case, is there still a need for a function too? (assuming that these two values are documented)

**Comment by dsheets** [comment]
This was fixed by #48.
