### ISSUE TITLE
Configurable resolver timeout and retries

### ISSUE THREAD

**Issue by dsheets** [mirage/ocaml-dns#77]
This isn't configurable and should be. It should probably be specified during the creation of the resolver value.

**Comment by SGrondin** [comment]
:+1:

**Comment by hannesm** [comment]
In the current state of work, the API of dns-client is most useful for OCaml applications. And this indeed has a timeout parameter. The retry is not much of a concern, since the dns-client uses TCP or TLS for requests, but not UDP.

The dns-resolver - a recursive resolver - indeed has timeouts and retries for queries.
